# Generated by Django 4.2.16 on 2024-09-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id_enseignant', models.AutoField(primary_key=True, serialize=False)),
                ('nom_enseignant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom_etudiant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.AutoField(primary_key=True, serialize=False)),
                ('nom_salle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_obtenue', models.IntegerField(max_length=5)),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSec.cours')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSec.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='id_enseigant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSec.enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='id_salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSec.salle'),
        ),
    ]
