# Generated by Django 4.2.16 on 2024-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='id_enseigant',
            new_name='id_enseignant',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_obtenue',
            field=models.IntegerField(),
        ),
    ]
